[package]
name = "corvid-fuzz"
version = "0.0.0"
publish = false
edition = "2021"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"

[dependencies.corvid]
path = ".."

[[bin]]
name = "frame_fuzzer"
path = "fuzz_targets/frame_fuzzer.rs"
test = false
doc = false
bench = false

[[bin]]
name = "session_fuzzer"
path = "fuzz_targets/session_fuzzer.rs"
test = false
doc = false
bench = false

[[bin]]
name = "codec_fuzzer"
path = "fuzz_targets/codec_fuzzer.rs"
test = false
doc = false
bench = false

[profile.release]
debug = true
